# Generated by Django 6.0 on 2025-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAcademic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idCard',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
